### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by Cha0sJ** [gooderbrother/antiVirusCheck#1]
cs4.1加载之后识别会乱码，然后会指向192.168.174.1.但是这个IP跟我毫无关系，怎么回事呢

**Comment by raspberryhusky** [comment]
> cs4.1加载之后识别会乱码，然后会指向192.168.174.1.但是这个IP跟我毫无关系，怎么回事呢

乱码是脚本保存在本地时编码格式的问题，用编辑器打开保存格式设置成utf-8；指向和你毫无关系的ip不应该呀，指向的应该是当前运行脚本beacon的ip呀

**Comment by raspberryhusky** [comment]
> cs4.1加载之后识别会乱码，然后会指向192.168.174.1.但是这个IP跟我毫无关系，怎么回事呢

兄弟，ip地址不对的问题修复了，把获取ip地址的方法改成了binfo($1)['internal'])，下载最新的试试吧

**Comment by Cha0sJ** [comment]
好的，才看到，蟹蟹大佬
