### ISSUE TITLE
乱码问题2

### ISSUE THREAD

**Issue by Cha0sJ** [gooderbrother/antiVirusCheck#2]
我这边尝试了，IP正确了，但是乱码问题依旧，我尝试了用记事本粘贴进去，保存的时候选UTF8 CS4.1直接就不识别了，用notepad++粘贴的话可以识别使用，但是还是乱码，编码格式已经是UTF8了

**Comment by raspberryhusky** [comment]
> 我这边尝试了，IP正确了，但是乱码问题依旧，我尝试了用记事本粘贴进去，保存的时候选UTF8 CS4.1直接就不识别了，用notepad++粘贴的话可以识别使用，但是还是乱码，编码格式已经是UTF8了

如果还是UTF-8不行就是试试GBK，市面上魔改版的cs太多了，编码也不一样

**Comment by Cha0sJ** [comment]
我试了一下 GBK可以的 YYDS！
